[mysqldb]
user = "root"
password = "Aaibaba"
port = 3306
host = "127.0.0.1"
database = "starwarsDB"


#[swapi]
#home_url = "https://swapi.dev"
#vehicle = "/api/vehicles"
#starship = "/api/starships"
#film = "/api/films"
#